docs/webassembly.md
Fixed some TOML formatting and fixed a structural problem in some of the WASM docs.
=> fixed some TOML issues

Cargo.lock, examples/client.rs, src/client/mod.rs, src/standalone/mod.rs
This allows us to use streams properly and updates all files
=> ref(*): Updates reqwest to 0.10.10

bin/client/main.rs, src/cache/dumb.rs, src/filters/mod.rs, src/server/handlers.rs, src/server/mod.rs, src/storage/file/mod.rs, src/storage/mod.rs, tests/standalone.rs
As we have gone along with client implementations, I realized that we
were always converting things from streams into readers. Because this
is an HTTP API, it should be expecting an arbitrary stream of data from
somewhere rather than a reader of some kind.
This also fixes some clippy lints I found
=> ref(storage): Updates the storage trait to use streams

docs/bindle-spec.md, docs/invoice-spec.md, docs/reference-spec.md
First draft on a naming specification for Bindle.
=> add reference specification

Cargo.toml, src/server/reply.rs
This will need a 0.3.1 release and a yank of 0.3.0 (since it has compilation issues)
=> fix(*): Fixes some feature flag issues that caused compilation errors

bin/server.rs
Ref: #87
Default config file name is `server.toml` in the directory set by the
`dirs` crate.
https://docs.rs/dirs/3.0.1/dirs/fn.config_dir.html
=> feat(server): Add optional config file

docs/label-spec.md
=> fix label spec typo

bin/client/main.rs
Make sure that the config dir exists before attempting to use it.
Closes #116
=> ensure that a config directory exists before trying to use it

Cargo.toml, src/cache/dumb.rs, src/cache/lru.rs, src/client/load.rs, src/client/mod.rs, src/provider/file/mod.rs, src/standalone/mod.rs
=> chore(*): Added tracing to client

src/server/filters.rs
=> log server-side warning when TOML fails to parse

docs/webassembly.md
=> Update to newer Wasm/WASI directions

docs/protocol-spec.md
=> doc(spec): Better documents the missing parcels body

bin/client/main.rs, bin/client/opts.rs, bin/server.rs
Both of these issues were similar and small enough to fit into one PR.
Closes #123
Closes #121
=> fix(*): Uses XDG based locations as defaults for data storage

src/invoice/label.rs, src/provider/file/mod.rs, src/provider/mod.rs, src/search/strict.rs, src/server/reply.rs
This partially implements #148. I wasn't sure whether we should handle this on the client side or not. See the issue for more discussion on this point.
=> feat(server): Adds check against parcel length before saving

Cargo.toml, src/server/filters.rs, src/server/reply.rs, tests/client.rs
=> fix(server): Allows for proper parsing of charset

src/provider/file/mod.rs
This has some small improvements to the new `PartFile` to make sure that it
takes a file "lock" right when it is created. It also refactored the `create_invoice`
method to use the new `PartFile`. I also added a test to at least give
us a sanity check that a double write doesn't cause an issue
=> fix(provider/file): Uses partfile for invoice and improves locking

src/client/mod.rs
By default, the Bindle client goes straight to HTTP/2 when talking to a Bindle server.  This is usually safe because the Bindle server speaks HTTP/2.  However, on certain occasions, certain rare and vexatious occasions, when the Bindle server is hidden behind a proxy or tunnel, a low, brutish proxy or tunnel that clings to savage, degraded protocols such as HTTP/1.1.  The Bindle server is perfectly happy being talked via such a proxy or tunnel, but the _client_ cannot establish communication because the oafish, ignorant proxy fails to comprehend its initial HTTP/2 greeting.
For these cases, these sad cases, it is useful to be able to have the client approach the proxy using HTTP/1.1 (and request an upgrade to HTTP/2).  In my sample of 1 tunnelling service, this worked 100% of the time. …
=> Option to negotiate HTTP/2 instead of assuming

.github/workflows/rust.yaml, Makefile, bin/as2bindle.rs, bin/cargo2bindle.rs, bin/client/main.rs, bin/server.rs, src/cache/dumb.rs, src/client/mod.rs, src/filters/mod.rs, src/id.rs, src/invoice/mod.rs, src/invoice/signature.rs, src/invoice/verification.rs, src/provider/file/mod.rs, src/server/handlers.rs, src/server/mod.rs, src/server/routes.rs, src/standalone/mod.rs, src/testing/mod.rs
This PR consists of several mostly atomic commits that do some cleanup and small refactors that were much needed (it has been a while since we last cleaned up the code). Each commit explains specifically what was done and why, so I would recommend reviewing each commit separately when reviewing.
=> The Clone Wars: Attack on the Clones

src/server/reply.rs
This switches the `Accept` header parsing to use more of the `mime` library. However, since that library doesn't have support for `application/toml`, at the end of the day it is still about 80% string manipulation. For consistency, I have left the JSON handling as-is, too.
Closes #154
=> use MIME library for parsing headers

README.md, bin/client/opts.rs, docs/README.md, examples/client.rs, tests/cli.rs
See https://github.com/deislabs/hippofactory/issues/25 for discussion
Closes #170
=> Rename BINDLE_SERVER_URL to BINDLE_URL

src/provider/file/mod.rs
Based on the documentation for the windows specific code, it looks like
the share mode is set to allow other processes to read/write/delete the
file. This removes those permissions so that it should stop a new file
from being simultaneously created.
Closes #173
=> fix(file): Ensures that windows part file actually locks

src/invoice/signature.rs, src/server/reply.rs
=> fix(signature): Ensures that a saved key has 0700 bits on unix

src/server/reply.rs
Our current implementation just to_string'd things for nested errors. This
led to very confusing errors for the user. Now this un-nests stuff to get a
a better message to the user for client errors
Before:
```
Invalid request (status code 400): Some("failed signature check invoice")
```
After:
```
Invalid request (status code 400): Some("no suitable key for signing data")
```
Closes #193
=> feat(server): Improves errors returned from proxies and signature issues

bin/server.rs
There were places we were returning the IO errors from server startup without
adding any context. This maps those errors to more useful messages in case
of a failure.
Closes #185
=> ref(server): Handles IO errors more gracefully

docs/README.md
=> add docs about key file formats

README.md
=> A missive from Noki, god of nits

bin/client/main.rs, bin/client/opts.rs
=> feat(client): add json output to bindle info

Cargo.lock, Cargo.toml, docs/README.md
=> Updated versions to 0.6.0

README.md
=> typo in build instructions

README.md
Signed-off-by: Michelle Noorali <michellemolu@gmail.com>
=> fix(README.md): fix typo. connections -> connects

bin/client/main.rs, bin/client/opts.rs
Add insecure flag for ignoring certificate errors.
=> feat(client): add insecure flag

bin/client/main.rs, bin/client/opts.rs, bin/server.rs, src/invoice/signature.rs, tests/cli.rs
This was going to be part of the PR for adding verification to the client, but it had already gotten big enough that I decided this should be its own PR. See the individual commit messages for more specifics on what has been added
=> Adds CLI commands and loading functions to assist with key management

bin/client/opts.rs, bin/server.rs, examples/as2bindle.rs, examples/cargo2bindle.rs, src/cache/mod.rs, src/client/load.rs, src/filters/mod.rs, src/provider/embedded.rs, src/search/strict.rs, tests/client.rs
this is just a simple fix on typos on the docs and `.rs` files to help improve documentation !!
=> minor fix on typos to improve documentation

docs/README.md
simple update to 'Using Bindle' section of the docs to stay current
=> fix(doc)-minor update the 'Using Bindle' section to stay current

src/client/mod.rs
=> fix(cli)-minor-replace the hardcoded bad request error message

.github/workflows/release.yaml
https://github.com/bacongobbler/azure-blob-storage-upload/releases/tag/v2.0.0
=> azure-blob-storage-upload v2.0.0

.github/workflows/release.yaml
Signed-off-by: Matthew Fisher <matt.fisher@fermyon.com>
=> add overwrite option

src/standalone/mod.rs
Pushing a bindle that contains many assets using `StandaloneRead::push` can
result in a "too many open files" error on POSIX systems with a default file
descriptor limit of 1024.  This is due to the unlimited concurrency of
`future::join_all`.
The alternative is to use `futures::StreamExt::buffer_unordered` instead, which
accepts a parameter to limit maximum concurrency.
This fixes https://github.com/deislabs/bindle/issues/336.
Signed-off-by: Joel Dice <joel.dice@gmail.com>
=> fix: address "too many open files" error when pushing large bindles

docs/README.md
The link had a error in the path.
=> Fixes link on README.md

README.md
Seeing as many of us are using this for real, removing the "not in production" warning felt like the right call here
=> Removes warning about not using in production

.github/workflows/fixblob.yaml
This is a one off CI pipeline we will remove once we run it once, but it should checkout and rebuild all versions.
=> fix(ci): Fixes missing blobs

Dockerfile
Also upgrade to Rust 1.64 in the Dockerfile.
=> Use Debian as base image in Dockerfile

bin/server.rs
This automatically adds the keys from signing-keys.toml to the keychain and adds the auto-generated host key to the keychain as well.
Fixes #356
=> fix(server): Adds default host keys and signing keys to keychain

Cargo.lock, Cargo.toml, examples/as2bindle.rs, examples/cargo2bindle.rs, src/cache/lru.rs, src/server/routes.rs, tests/standalone.rs
I also fixed some new clippy warnings that popped up and some odd warnings from warp that we hadn't seen before
=> chore(*): Bumps version to 0.9.0
