- src/client/mod.rs
- tests/client.rs
Right now the client will return an error if an invoice is created
that already has all of its parcels. This adds the missing HTTP code
mapping to fix that issue.
> fix(client): Fixes missing HTTP code mapping

- bin/client/main.rs
- src/cache/dumb.rs
- src/client/mod.rs
- src/lib.rs
- src/provider/file/mod.rs
- src/provider/mod.rs
- src/proxy/mod.rs
- src/server/handlers.rs
- src/server/mod.rs
- src/server/reply.rs
This is a simple proxy provider that forwards requests to a bindle server. It
also necessitated changes to the provider API to account for proxying. The
only part of it I am not completely sure about is the `'static` bound I had
to add. I _think_ it makes sense as we need to make sure the stream lives long
enough, but I am not sure if there could be a better way.
> feat(*): Adds new proxy provider

- tests/cli.rs
The CLI integration tests were not using temporary directories for caching
bindles, which led to weird successes in local testing
> fix(tests): Makes sure to use tempdir for cache

- Cargo.lock
- Cargo.toml
- bin/as2bindle.rs
- bin/cargo2bindle.rs
- bin/client/main.rs
- bin/server.rs
- examples/client.rs
- src/async_util.rs
- src/cache/dumb.rs
- src/client/load.rs
- src/client/mod.rs
- src/provider/file/mod.rs
- src/provider/mod.rs
- src/provider/test_common.rs
- src/proxy/mod.rs
- src/server/filters.rs
- src/server/handlers.rs
- src/standalone/mod.rs
- src/testing/mod.rs
- tests/client.rs
- tests/standalone.rs
- tests/test_util.rs
I did have to make one small trait constraint change to the `Provider`
trait to accomodate using the tokio util library. This also removes the
ReadBodyBuffer type as there is an included type in tokio util now
> chore(*): Updates all libraries to use tokio 1.0

- src/server/handlers.rs
This reference was causing build failures when only using the `server` feature as we don't import reqwest for that
> fix(server): Remove reference to reqwest

- Cargo.toml
- src/provider/file/mod.rs
This will avoid multiple fetches of the invoice from the file system on a
bindle that has a large number of parcels
> feat(provider): Adds invoice caching to file provider

- src/provider/file/mod.rs
- src/provider/mod.rs
- src/server/reply.rs
The file provider had a possible race condition where 2 people try to create
the same file or if someone tries to create and read at the same time. This
resolves that by writing first to a "part" file and then renaming it. It also
adds documentation to the provider trait that terminal providers should take
care to handle atomic operations or locking
> fix(provider): Fixes race condition with file provider

- Cargo.lock
Our current deps referenced a few yanked versions and it wasn't compiling
on my Mac when trying to publish. This is the lock file used to publish 0.3.1
> fix(*): Updates dependencies to latest patch

- docs/signing-spec.md
This defines an `approver` role and goes into more detail about how verification works in Bindle.
> Define the `approver` role

- docs/invoice-spec.md
The version text in the sample in the invoice spec had gotten out of sync with modern thinking, and caused errors if you tried to serve the invoice from the spec.  This PR aligns the sample to the (presumably validated) test data.
> Fix versions in invoice spec sample

- bin/as2bindle.rs
- bin/cargo2bindle.rs
- docs/signing-spec.md
- src/invoice/mod.rs
- src/invoice/signature.rs
- src/search/strict.rs
This brings the current signature library into parity with the current signing spec.
- Adds yanked_signature
- Adds keyring
- Adds key entry
- Adds key entry signing
- Fixes a snake_case typo in the spec
> added library support for yanked signature and keyring

- docs/invoice-spec.md
- docs/label-spec.md
- src/invoice/label.rs
- src/invoice/mod.rs
- test/data/simple-invoice.toml
This PR adds `origin` to `Label` and updates the spec to explain how to use it for tracking provenance.
> add origin field to label for provenance

- src/invoice/mod.rs
- src/invoice/signature.rs
This is an addition to the Keyring code, adding a way to verify that the label on a key entry has not been tampered with.
> added a verify_label function to the key entry

- bin/client/main.rs
- bin/client/opts.rs
- src/invoice/mod.rs
- src/invoice/signature.rs
- src/lib.rs
- tests/cli.rs
Add support for creating and reading keyfiles. Adds `bindle create-key` command.
Closes #103
> Add CLI command to create keyfile.

- bin/client/main.rs
- bin/client/opts.rs
- src/client/error.rs
- src/invoice/mod.rs
- src/invoice/signature.rs
- tests/cli.rs
This is the third step toward implementing signing and verification. It uses a key created with `create-key` and signs an invoice.
> add sign-invoice command

- bin/client/opts.rs
In the client, some commands say they take `BINDLE` for an argument, but don't specify what `BINDLE` is. I added a tiny bit of documentation.
> added a few about strings on commands that are confusing

- Makefile
- README.md
- bin/client/opts.rs
- docs/README.md
This updates the docs and adds a `Makefile` that hides away the growing complexity of our cargo commands.
Closes #125 
> update docs, add Makefile

- Cargo.lock
- Cargo.toml
- Makefile
- bin/client/main.rs
- bin/server.rs
- src/cache/dumb.rs
- src/cache/lru.rs
- src/client/error.rs
- src/client/mod.rs
- src/invoice/mod.rs
- src/invoice/signature.rs
- src/provider/file/mod.rs
- src/search/mod.rs
- src/search/noop.rs
- src/search/strict.rs
- src/server/filters.rs
- src/server/handlers.rs
- src/server/mod.rs
- src/server/reply.rs
- src/server/routes.rs
- src/standalone/mod.rs
This adds _a lot_ more tracing and instrumentation on most of the major functions
used for the server. It also adds in tracing to the warp processing pipeline, which
should help with debugging. The client code still needs to be updated with more logs
and with instrumentation, but I will do that in a follow up.
Please note that if you think the logs are too verbose or you don't like the format,
tracing is very very tweakable, so we can iterate on this and change it
> chore(*): Switches to the `tracing` crate and instruments all server things

- Makefile
- src/search/strict.rs
The previous implementation of search was stricter than the specification required. This relaxes strict processing.
The following should now work:
- an empty query
- an empty version filter
- a query whose term is a substring (e.g. `warp` should now match `enterprise.com/warpcore/1.0.0`)
Closes #98
> fix strict query processing

- bin/client/opts.rs
This fixes the help text for the `bindle search`'s `-q` option.
Before, the text erroneously said that `-q ""` would return all results. Attempting this would result in an error. In practice, merely omitting the optional `-q` flag is sufficient to get all results.
It also erroneously stated that the query had to be the name of the bindle. In strict mode, the query must be part of the name. But in standard mode, the query could be applied to authors, description, version, and other fields as well.
Closes #124
> fixed the help text for the search -q param

- Makefile
- bin/server.rs
- src/server/filters.rs
- src/server/handlers.rs
- src/server/mod.rs
- src/server/reply.rs
- src/server/routes.rs
Add content negotiation for JSON and TOML.
This adds support for using the `Accept` header to try to find the best format for sending results back. In addition, it accepts `invoice.json` content if the `content-type` is one of `text/json` or `application/json`.
Closes #132
> add Accept-type negotiation for JSON and TOML

- bin/server.rs
I found out that krustlet wasn't respecting it for the same reason, so
I added the change here as well
> fix(server): Respects RUST_LOG variable

- docs/invoice-spec.md
Per a long discussion with @itowlson, we have decided that a parcel that is a member of no groups is a non-feature. It means that there are parcels that must be present on the server, but which are never pulled. At best, it is a way of hiding data that a user could be directed to pull directly (via `curl`, for example). At worst, we made it really easy to hide nefarious stuff on a Bindle server.
> removed the concept of empty groups from spec

- src/client/mod.rs
Provide an option for consumers of the Bindle client crate to support "invalid" (typically self-signed) certificates.  E.g. hippofactory could add a `-k` option so it could push to a dev Bindle server or avoid Let's Encrypt Ubuntu woes.
> Allow consumers to set "insecure" mode

- Makefile
- src/invoice/mod.rs
This adds a `group_members(name)` function on the invoice so that it is easy to get all of the parcels that belong to a group.
Ported over from Wagi.
> add a group_members function on invoice

- bin/client/main.rs
- bin/client/opts.rs
- bin/server.rs
- docs/signing-spec.md
- src/cache/dumb.rs
- src/cache/lru.rs
- src/invoice/mod.rs
- src/invoice/signature.rs
- src/invoice/verification.rs
- src/provider/file/mod.rs
- src/provider/mod.rs
- src/proxy/mod.rs
- src/server/handlers.rs
- src/server/mod.rs
- src/server/reply.rs
- src/server/routes.rs
- src/testing/mod.rs
This PR wires up all of the signing and verification logic for the server.
Todo:
> Verify creator on invoice upload

- docs/signing-spec.md
- src/invoice/verification.rs
- src/provider/file/mod.rs
As I started to work on #143, I realized that we technically have 2 Mulitple Attestation
strategies that would be better to explicitly document and define rather than having
that behavior defined by a boolean flag. This also has the side effect of making parsing a config
object and command line flag easier to implement for #143
> feat(verification): Updates with new verification strategy

- bin/client/main.rs
- src/client/error.rs
- src/id.rs
- src/provider/mod.rs
- src/server/reply.rs
This results in error output that walks the nested errors and prints the root cause:
```console
$ bindle --server $BINDLE_HOST push foo
Error: Invalid id: InvalidId("foo")
Caused by:
Invalid bindle ID foo. A bindle ID should be NAME/VERSION
$ bindle --server $BINDLE_HOST push foo/bar/dadsfas
Error: Invalid id: InvalidSemver("dadsfas")
Caused by:
ID does not contain a valid semantic version (e.g. 1.2.3): dadsfas
```
Closes #159
> Reworked error output for ID and SemVer parse errors

- bin/server.rs
- src/invoice/signature.rs
- src/invoice/verification.rs
- src/server/handlers.rs
- src/server/mod.rs
- src/server/routes.rs
You are now able to specify the verification strategy with a command line
flag or an item in the config file. This ended up being a bit more involved
than we initially thought due to the need to implement a custom deserialize
for the strategy
Closes #143
> feat(server): Adds configurable verification strategy

- Makefile
- src/invoice/mod.rs
- src/provider/file/mod.rs
- src/standalone/mod.rs
When pairing with @adamreese on https://github.com/deislabs/wagi/issues/79, I noticed that we had some missing features on `StandaloneRead`. This adds accessors to the invoice and parcels so that client users do not have to know anything about the file structure of a standalone bindle.
Also refactored the `Makefile` because I am impatient and want to run tests faster.
> added accessor methods for StandaloneRead

- Cargo.lock
- Cargo.toml
- docs/README.md
- docs/crate-readme.md
- src/invoice/mod.rs
Somehow we missed this in the review so technically the trait was wide
open. This seals the trait and bumps the version in one go and then I'll
yank 0.4.0
> fix(*): Marks `Signed` trait as `Sealed`

- .github/workflows/rust.yaml
- Cargo.lock
- deny.toml
This adds package auditing and `cargo deny` to the build workflow for
bindle. This should inform us if we are using any projects with security
advisories or ones we have explicitly denied (none right now). This will
also run a license check to make sure we are at least using licensed
projects. It can be tweaked to allow specific licenses in the future.
As part of this, I have addressed any changes it found
> feat(*): Adds `cargo deny` to build pipeline

- docs/invoice-spec.md
- docs/label-spec.md
This describes label annotations, defines two reserved annotations, and clarifies invoice annotations.
Closes #182 
> Spec: describe annotations and reserved annotations

- bin/client/main.rs
- bin/client/opts.rs
This prints the public key entry for a private key in a bindle client's `secrets_keys.toml` or a bindle server's `signing-keys.toml` file.
Example:
```console
$ bindle print-key
version = "1.0"
[[key]]
label = "Matt <example@example.com>"
roles = ["creator"]
key = "Qx6Q8d0K8sb0828S8hivB9ev+CWB+i1jqv596F3MbFQ="
labelSignature = "v6trXDbBKLl+9dXgmNlySajcPYHTeqwPy3Zy+PybD5qKGfPoMhkEp1pnkpSWHz5KT1F5yGxyUAvk4EbFmW7KDg=="
```
Note that you can use `--label` to filter to only keys whose label matches. This is approximately consistent with the way GPG works.
```console
$ bindle print-key --label Matt
version = "1.0"
[[key]]
label = "Matt <example@example.com>"
roles = ["creator"]
key = "Qx6Q8d0K8sb0828S8hivB9ev+CWB+i1jqv596F3MbFQ="
labelSignature = …
```
> add print-key command

- bin/client/opts.rs
Change BINDLE_DIR to BINDLE_DIRECTORY in the client options to match the server options.
Closes #181
> Make client use same env var as server

- tests/cli.rs
- tests/client.rs
- tests/test_util.rs
I believe that the slowness of the GH runners was creating issues when using
`cargo run` to run the server binary - even after previously building it. This
changes things to run the built binary directly instead, avoid the overhead of
"rebuilding" it. It also makes things more generic so people consuming test
utils are not required to have a specific binary name
> fix(tests): Attempts to fix macos flake

- src/client/mod.rs
fixes #202
Before:
```
><> bindle --server https://bindle.f1sh.ca:8080/v1 search
Error creating request
Error trace:
1: error sending request for url (https://bindle.f1sh.ca:8080/v1/_q): http2 error: protocol error: frame with invalid size
2: http2 error: protocol error: frame with invalid size
3: protocol error: frame with invalid size
```
After:
```
><> bindle --server https://bindle.f1sh.ca:8080/v1 search
query = ""
strict = true
offset = 0
limit = 50
total = 0
more = false
yanked = false
invoices = []
```
> default http2_prior_knowledge to false

- bin/client/main.rs
- src/invoice/signature.rs
After doing some digging, it looks like `flush`ing the file after write solves the problem. My theory, which I cannot entire prove, is that because the CLI stops execution, the file write did not complete, particularly on slower systems like the GH Action runners. So now we make sure to manually flush the file in places where we are not using the `write` style helper functions. I fixed this anywhere in the CLI it was not flushing. I also noticed that the logic as specified in the `create-key` command would not work with the current `save_file` method as it was using `create_new` to save the file. This changes it to `create` so that it can overwrite the existing file
> fix(*): Fixes flaky windows test

- Cargo.lock
- Cargo.toml
- Makefile
- bin/server.rs
- src/provider/embedded.rs
- src/provider/mod.rs
- src/server/mod.rs
- src/testing/mod.rs
- tests/test_util.rs
This PR adds support for a new embedded `Provider` backed by the `sled`
embedded database and with more efficient data encoding. This new
provider is behind a feature flag and is not compiled into `bindle-server`
by default. Tests have also been updated to check both providers, but
the client tests still only test with the `FileProvider`.
The motivation behind this is that the file system provider requires a bunch of
bespoke logic to check things like locking and various OS specific things. We
also have to front everything with an in-memory LRU cache. Tools like `sled`
already have most of these features built in, plus additional guarantees from
being a database (such as atomic transations and upsert commands). This also
uses a binary encoding format to store the data using less bytes and …
> exp(provider): Adds support for experimental embedded provider

- .github/workflows/release.yaml
We forgot to change the build pipeline to look for main instead of master
so canary releases haven't been building
> fix(ci): Updates references from master

- src/client/error.rs
- src/client/mod.rs
All 404s were getting interpreted as missing index/parcel. Turns out some 404s occur because the endpoint is missing. So this at least tries to distinguish between the two situations.
> Provide better errors for non-GET operations

- src/invoice/signature.rs
Fixes #192 
Generate key file permissions switched from 0o700 (RWX) to 0o600 (RW).
Signed-off-by: Nitish Malhotra <nitish.malhotra@gmail.com>
> Generated key-file.toml should have RW perms

- Cargo.lock
- Cargo.toml
- bin/client/main.rs
- bin/client/opts.rs
- bin/server.rs
- deny.toml
- docs/protocol-spec.md
- src/authn/github.rs
- src/authn/mod.rs
- src/client/mod.rs
- src/invoice/api.rs
- src/invoice/mod.rs
- src/server/handlers.rs
- src/server/routes.rs
So this is a bit gnarly here, but functional. Basically, the login flow goes like this:
Client calls `/login` endpoint with their desired provider -> bindle server starts device code flow ->
bindle server returns auth code details to client -> client calls proper endpoint to retrieve token
On every API call, the passed token will be validated against the auth provider. We will likely
want to optimize this with some sort of cache in the future. Ideally, we can add other providers
in the future using OIDC.
Closes #209
> feat(server): Adds Github authentication support to the server

- bin/client/main.rs
- bin/client/opts.rs
- src/client/error.rs
Add support for `-f`|`--format`. (Note that I didn't use `-o`|`--output` because we have already used it as a flag for output files)
The new formatter gives users the choice between `table` (new default), `toml`, and `json`. It is easy enough to add other serializers.
New default output:
```console
$ bindle search -q example
example.com/hello/1.0.0:        Autogenerated example bindle for Wagi
example.com/hello/1.1.0:        Autogenerated example bindle for Wagi
example.com/hello/1.2.0:        Autogenerated example bindle for Wagi
example.com/hello/1.3.0:        Autogenerated example bindle for Wagi
example.com/hello/1.3.1:        Autogenerated example bindle for Wagi
example.com/hello/1.3.2:        Autogenerated example bindle for Wagi
example.com/hello/1.3.3:        Autogenerated …
```
> add --format to search

- Cargo.lock
- Cargo.toml
- bin/server.rs
- src/authn/http_basic.rs
- src/authz/always.rs
- src/authz/anonymous_get.rs
- src/authz/mod.rs
- src/server/filters.rs
- src/server/mod.rs
- src/server/routes.rs
- tests/cli.rs
- tests/client.rs
The major change here is that now if no authorization header is passed
authentication will be "successful" and pass on anonymous auth instead.
> feat(server): Adds anonymous auth support for get endpoints

- bin/server.rs
Make `use_db_embedded` field optional to prevent toml parsing errors
when not set.
Closes: #212
> Respect config file values

- src/server/routes.rs
This boxes the warp filters so that the compile-time checks do not take 5-15 minutes.
> Box Warp filters to speed up build time

- bin/client/main.rs
Previously if you had a bad token file (like, one left over from a previous go at Bindle auth) it gave you
```
Invalid TOML
Error trace:
1: expected an equals, found eof at line 1 column 41
```
which didn't help you resolve it.
With this change it gives you:
```
Invalid configuration: Error loading token file "/home/ivan/.config/bindle/.token": Invalid TOML
```
which is hopefully enough to track down the problem and decide what you want to do about it.
Fixes #228.
> Clearer error on bad token file

- bin/server.rs
- tests/standalone.rs
- tests/test_util.rs
Makes running bindle-server without authentication an explicit option.
Closes: #235
> Add unauthenticated flag to bindle-server

- Cargo.lock
- Cargo.toml
- src/invoice/mod.rs
This commit upgrades bindle's deps with `cargo upgrade`.
For almost all the deps, this just sets the patch version to the latest available, thus treating it as the minimum patch level for the given major.minor.
This specifically upgrades the `semver` crate to latest, as bindle was using a very old version that prevents downstream crates from using a newer version. As a result, a code change was required to maintain "npm" compatibility (which is no longer a thing in the `semver` crate).
The `dirs` create is upgraded to `4.0` with this change (API compatible).
The `rand` dependency was not updated as an upstream dependency uses a
backwards incompatible version.
> Upgrade deps with `cargo upgrade`.

- src/client/error.rs
- src/client/mod.rs
This traps networking errors and makes a noble effort to be informative.
Most, if not all, network errors will be due to either network failure or pointing at the wrong URL. This PR tries to catch those that result in hitting the wrong URL.
Server responds 400 BAD REQUEST:
```
$ bindle --server http://bindle.f1sh.ca:8080/v1 search
Server has encountered an error: The request could not be handled by the server. Verify your Bindle server URL
```
A networking error occurred during connection (e.g. wrong port, server disconnects abruptly):
```
$ bindle --server http://bindle.f1sh.ca/v1 search
Server has encountered an error: Protocol error. Verify the Bindle URL
```
Closes #231 
> improve error messages for network connection failures

- .github/workflows/release.yaml
This was missed in https://github.com/deislabs/bindle/pull/248
> Remove cargo2bindle and as2bindle from the release action

- Makefile
I was following the steps in the README around [starting the server](https://github.com/deislabs/bindle#starting-the-server), specifically:
`If you would like to run the server with cargo run (useful when debugging), use make serve or make serve-tls. (The first time you run make serve-tls, it will prompt you to create a testing TLS cert.)`
When I ran `make serve`, I encountered the following error:
```
$ make serve
cargo run --features cli --bin bindle-server -- --directory  --address 127.0.0.1:8080   --unauthenticated
Finished dev [unoptimized + debuginfo] target(s) in 0.52s
Running `target/debug/bindle-server --directory --address '127.0.0.1:8080' --unauthenticated`
error: The argument '--directory <bindle_directory>' requires a value but none was supplied
```
Therefore, this PR …
> fix(Makefile): add default value for BINDLE_DIRECTORY var

- .github/workflows/release.yaml
- .github/workflows/rust.yaml
- Cargo.toml
We've been tracking and using most of the latest features anyway, so
this seems to make sense
> chore(*): Bumps bindle to use the 2021 edition

- .github/workflows/rust.yaml
- Cargo.lock
- Cargo.toml
- bin/client/main.rs
- bin/client/opts.rs
- bin/server.rs
- deny.toml
- src/authn/oidc.rs
- src/client/mod.rs
- src/client/tokens.rs
- src/invoice/mod.rs
- src/invoice/signature.rs
- src/invoice/verification.rs
This updates a bunch of dependencies that were causing cargo deny issues and other compilation problems. Please note that I still had to ignore the omnipresent `time` and `chrono` RUSTSEC advisories as `openid` has not updated. I plan on submitting a PR to use the `time` crate instead over there to fix the issue and then those could be removed. However, I did address all other direct and transitive imports of `chrono`
> Fixes cargo deny and update dependencies

- docs/invoice-spec.md
- docs/webassembly.md
- src/standalone/mod.rs
There were a few erroneous references to the word "bundle" instead of
"bindle". This commit replaces them appropriately.
Signed-off-by: Radu Matei <radu.matei@fermyon.com>
> fix: replace references of "bundle" with "bindle"

- docs/reference-spec.md
* Fixes the SemVer 2 link in the Reference Spec doc
> docs(reference-spec.md): fix SemVer 2 link

- Cargo.lock
- Cargo.toml
* Bumps the tracing-subscriber dependency per https://github.com/deislabs/bindle/issues/279
I noticed that `cargo build` automagically bumped the bindle version via a patch increment to 0.7.1 -- handy!
Closes https://github.com/deislabs/bindle/issues/279
> chore(Cargo.toml): bump tracing-subscriber dependency per #279

- src/invoice/signature.rs
- src/invoice/verification.rs
This addresses an issue when consuming the `bindle` crate in WAGI (and, no doubt, other applications): the `ed25519_dalek::Signature::from_bytes`, used in `invoice/signature.rs` and `invoice/verification.rs`, method is actually on the `signature::Signature` trait which is not in scope in those files.  I don't yet understand why those files would compile in the Bindle client and server, but they don't compile in WAGI.  And adding the trait to the files makes them give an "unused import" warning in Bindle!
The fix is to instead use Signature's `TryFrom` implementation, which is documented in the Signature examples, doesn't need to be brought into scope, and delegates directly to `from_bytes` so shouldn't change any behaviour #famouslastwords.
@vdice would be great if you could give this a …
> Fix for crate consumers not finding Signature trait methods

- Cargo.lock
- Cargo.toml
- docs/README.md
* Bumps the version to the next minor release
This is more a 'suggestion to release'.  I'm not as up-to-speed on if we wanted to wait for certain features/changes before releasing 0.8.0 or not.  My motivation stems from https://github.com/deislabs/wagi needing the changes in #287 to succesfully rev its bindle version to the latest and greatest.
As it stands, this is the changelog since 0.7.1:
- chore(Cargo.toml): bump version to 0.8.0 c94e4aa7ff39cc415ca353e795510cc5b3f9e868 (Vaughn Dice)
- Fix for crate consumers not finding Signature trait methods (#287) d46c3715adc58882ea6e95d388dad3eebce57e54 (itowlson)
- fix(ci): Uses the correct var name 053cb8a65b471869f2ae379dbda2321b220a0df8 (Taylor Thomas)
- feat(ci): Adds support for m1 Macs and auto crate pushing …
> chore(Cargo.toml): bump version to 0.8.0

- bin/client/main.rs
- bin/client/opts.rs
- bin/server.rs
- examples/client.rs
- src/cache/lru.rs
- src/client/mod.rs
- src/invoice/mod.rs
- src/invoice/signature.rs
- src/invoice/verification.rs
- src/provider/file/mod.rs
- src/server/mod.rs
- src/standalone/mod.rs
- src/testing/mod.rs
- tests/cli.rs
- tests/standalone.rs
- tests/test_util.rs
The default strategy is just to check that the host signature is valid, so
this shouldn't provide too much of a burden for people kicking the tires
> feat(*): Adds required verification to the client

- src/provider/file/mod.rs
This will now log an error when the bindle server initially tries to create
directories for invoices or parcels. I checked the embedded provider and these
kind of errors are caught on creation
Closes #297
> fix(file): Adds error log when IO errors occur on invoice/parcel create

- bin/client/opts.rs
- tests/cli.rs
I just went with the simple workaround of providing a default. It results in
the least amount of code changes and is easy to override with your own value
Closes #111
> ref(cli): Makes global bindle URL less annoying to work with

- docs/README.md
- docs/bindle-spec.md
- docs/keyring-protocol-spec.md
- docs/protocol-spec.md
This PR proposes a new specification section for a "Keyring protocol."
The purpose of this protocol is to enable easier key distribution for the
80% use case. Instead of being something intrinsic to the bindle protocol,
I believe having this as a separate protocol that any server (including existing
key servers) could implement will make it much more flexible.
If this spec change is accepted, I will implement it in a followup PR
> docs(spec): Adds new Keyring protocol spec

- Cargo.lock
- Cargo.toml
- src/invoice/api.rs
- src/invoice/mod.rs
- src/invoice/signature.rs
- src/provider/embedded.rs
- src/provider/file/mod.rs
- src/provider/mod.rs
Sometimes a dependent project may need just the types, so now when
no features are enabled, just the core types and traits are exposed.
This also takes a first pass at "optionalizing" as many dependencies
as possible. The dependency tree has gotten quite large, so this tries
to only import things when they are absolutely needed. We could probably
add a few more features (like on the auth stuff) to make it perfect, but
this was a good start
> ref(*): Better organizes features and dependencies

- docs/protocol-spec.md
This gives hosts flexibility in serving parcels from alternative services (CDN, IPFS, S3, etc).
> spec: Require clients follow redirects from parcel GETs

- Cargo.lock
- Cargo.toml
- bin/client/main.rs
- bin/client/opts.rs
fixes #280 
This PR adds `clean` subcommand to `bindle cli` to clear the DumpCache
> feat(cli): add `bindle clean` subcommand to clear the local cache

- Cargo.lock
- src/client/mod.rs
The current "Unknown error" is very hard to diagnose because it depends on the server providing everything you need in the message.  This is not a good thing to rely on, especially for unfortunate server devs trying to get their stuff working with the existing client, so this PR adds the following information to the "unknown error" message:
* The URL that produced the unexpected response
* The operation being carried out on that URL
* The status code that was returned
A minor change is that it will now say `Unknown error: (no error message in response)` rather than a trailing colon and space `Unknown error: `.  A complete message now looks like `Unknown error response: Create to http://localhost:5000/v1/_i/weather/1.2.3-ivan-20220317112555054@a4d030d845438e530f12cbf85422e82a65327443786e0c9 …
> Make "unknown error" client errors a bit more informative

- Cargo.lock
- Cargo.toml
I couldn't figure out exactly what was originally breaking that needed this workaround, but bindle seems to build fine now without it.
This pinned version was breaking when trying to link with `toml_edit` in spin due to a version constraint incompatibility.
> Remove pinned indexmap dependency

- .cargo/config
- .github/workflows/release.yaml
fixes #325
This PR adds step to build binary  for Linux aarch64 to Bindle releases
> feat(release):  build binary for ARM/aarch64 Linux in release workflow

- bin/client/main.rs
- bin/client/opts.rs
- src/invoice/signature.rs
- src/server/handlers.rs
- src/server/mod.rs
- src/testing/mod.rs
- tests/client.rs
fixes #299
this PR adds optional ability to `sign-invoice` with a key that matches the given label
```
❯ bindle sign-invoice -o signed-invoice.toml invoice.toml --label-matching "Vishnu Jin"
Signed invoice.toml with role creator, label as 'Vishnu Jin <vishnujin@outlook.com>' and wrote to signed-invoice.toml
```
```
❯ bindle sign-invoice -o signed-invoice.toml invoice.toml --label "Vishnu Jin <vishnujin@outlook.com>"
Signed invoice.toml with role creator, label as 'Vishnu Jin <vishnujin@outlook.com>' and wrote to signed-invoice.toml
```
> feat - add label search argument to sign-invoice

- src/server/routes.rs
fixes #331 
```
❯ curl http://localhost:8080/v1/_q\?q\=mybind -I                            
HTTP/1.1 200 OK
content-type: application/toml
content-length: 804
date: Thu, 14 Apr 2022 20:51:19 GMT
```
> Fix: head method not allowed for query `_q` path

- Cargo.lock
- Cargo.toml
This PR replaces the default TLS feature flag for `reqwest` with `rustls-tls` in order to eliminate the openssl dependency when using the `reqwest` crate. I went through a few iterations but couldn't quite find a way to cleanly keep the default-tls feature by default and then able `rustls-tls` optionally here, but I'm happy to implement that to keep the default behavior of this crate the same if desired. 
My main reason for doing this is so that I can depend on `bindle` without bringing in the openssl requirement which can be difficult to deploy across different versions of Linux
> Replaced reqwest's `default-tls` with `rustls-tls`

- bin/client/main.rs
- bin/client/opts.rs
- src/client/mod.rs
- src/invoice/api.rs
- src/invoice/mod.rs
- src/invoice/signature.rs
- src/provider/embedded.rs
- src/provider/file/mod.rs
- src/server/handlers.rs
- src/server/mod.rs
- src/server/routes.rs
- src/standalone/mod.rs
- src/testing/mod.rs
- tests/cli.rs
- tests/client.rs
This adds support for the new `bindle-keys` endpoint to the bindle server as well as client code for consuming that end point. Note that this has one small breaking change for the `raw` method on the `Client`. 
I also fixed some clippy lints that had snuck past us
> feat(*): Adds bindle-keys endpoint support

- Dockerfile
- Makefile
- docs/README.md
ref: https://github.com/fermyon/installer/pull/100
~It looks like [Using Bindle example](https://github.com/deislabs/bindle/tree/main/docs#using-bindle) can't work on the current master branch, so I use `v0.8.0` for testing.~ https://github.com/deislabs/bindle/pull/343#issuecomment-1250080411
**Start Bindle**
1. Clone this branch.
2. Run `git reset HEAD~1` to keep `Dockerfile`.
3. Run `git checkout v0.8.0` to check out to `v0.8.0`.
4. Run `docker build -t bindle .`.
5. Run `BINDLE_TEMP=$(mktemp -d)`.
6. Run `docker run --name bindle -d --restart=unless-stopped -e RUST_LOG=debug -v $BINDLE_TEMP:/bindle-data -p 8080:8080 bindle`.
**Start consul & nomad**
1. Run `consul agent --dev`
2. Run `nomad agent --dev`
**Start Hippo**
1. Clone the latest Hippo.
2. Run following commands.
```
export …
```
> Dockerize bindle

- docs/README.md
> fix(docs/README.md): add missing EOF

- .github/workflows/release.yaml
ref: https://github.com/fermyon/installer/issues/63, https://github.com/fermyon/installer/pull/100#issuecomment-1276462821
> feat: push docker image

- src/invoice/api.rs
- src/invoice/mod.rs
- src/server/routes.rs
resolve https://github.com/deislabs/bindle/issues/350
ref https://github.com/fermyon/spin/pull/786#issuecomment-1283146177
**Test step**
1. Build.
```
> make build
```
2. Run the server.
```
> ./target/debug/bindle-server --unauthenticated
```
3. Test `/healthz`.
```
> curl -i http://localhost:8080/healthz
HTTP/1.1 200 OK
content-type: application/json
content-length: 38
date: Thu, 27 Oct 2022 11:37:31 GMT
{"status":"OK","version":"0.9.0-rc.1"}
```
> feat(healthz): add version

- .github/workflows/release.yaml
> Bump azure-blob-storage-upload to v2.0.1

- Cargo.toml
- src/filters/mod.rs
- src/invoice/signature.rs
- src/invoice/verification.rs
- tests/cli.rs
- tests/test_util.rs
A while ago we made sure that if you wanted to pull in the base bindle types into something compiling to wasm, it would build. Recently, tokio made a change that made it so it wouldn't compile for wasm with the `fs` feature enabled. This makes sense, but I did have to untangle some fs stuff from the signatures module.
While I was here I fixed a bunch of new clippy lints from the latest version of clippy
> fix(wasm): Fixes deps for building in wasm

- .cargo/config
- .github/workflows/release.yaml
- deny.toml
@thomastaylor312 and @bacongobbler, does the following look like the right approach towards the goal of backporting some CI improvements/fixes into a v0.8.x release (would be v0.8.2 as of writing)?
Ref https://github.com/deislabs/bindle/issues/325
It incorporates both the [linux-aarch64 build support](https://github.com/deislabs/bindle/pull/328) and the [blob-store action bump/fix](https://github.com/deislabs/bindle/pull/355).  I ran the following:
```
git checkout release/0.8
git cherry-pick f7e31ccc5587c7444ef73bba702ec082f37cf345
git cherry-pick a5ba2c91cbfd7e1099c432cd4ae6c9e88b32f94a
```
**edit: also added this change to pass CI: https://github.com/deislabs/bindle/pull/359/commits/05d7a2557f12b399f44a2f1298df25f3349b6d47 ; ref …
> chore(release/0.8): cherry-pick CI features/fixes

- .github/workflows/release.yaml
Fix for error seen recently in the release workflow, eg https://github.com/deislabs/bindle/actions/runs/3679702313/jobs/6224462114
I tested with a fresh/stock Ubuntu 22.04 AMI in AWS.  Reproduced the error and it looks like the `apt-get update` indeed unblocks the apt installs.
> fix(release.yaml): add apt-get update in aarch64 build step

- .github/workflows/release.yaml
Cherry-picks the commit from https://github.com/deislabs/bindle/pull/360 to fix the release automation and unblock v0.8.2
Ref https://github.com/deislabs/bindle/issues/325
> fix(release.yaml): add apt-get update in aarch64 build step (#360)

- Cargo.lock
- Cargo.toml
Bumps the version to 0.8.2 on the release/0.8 branch; ref https://github.com/deislabs/bindle/issues/325#issuecomment-1360270947
I'll re-push the v0.8.2 tag once this is merged.
> chore(Cargo.toml): bump version to 0.8.2

- Cargo.lock
- Cargo.toml
- bin/client/main.rs
- src/authn/http_basic.rs
- src/authn/oidc.rs
- src/client/tokens.rs
- src/invoice/mod.rs
- src/invoice/signature.rs
- src/invoice/verification.rs
- src/server/mod.rs
This addresses a security vulnerability
> build: update `ed25519-dalek` and `base64`
